### ISSUE TITLE
Support for uninstalling packages

### ISSUE THREAD

**Issue by eabecho** [ghoneycutt/puppet-module-utils#19]
We have a need to enforce certain packages not be installed.

Can we expand utils to have a packages_absent parameter to enforce that certain packages are absent?  Or parse through the packages parameter and split out package names that are prefixed with '-' or perhaps '!'.

**Comment by ghoneycutt** [comment]
Hi @eabecho 

We should handle your case with the types module[1]. That way you can specify a hash of packages and if you want them to be present or absent. The code for each type is very similar, so you should be able to reuse most of the tests and framework by looking at a different type.

[1] - https://github.com/ghoneycutt/puppet-module-types
